version: 1
formatters:
  simple:
    format: '%(levelname)s - %(asctime)s - %(name)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  client-file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: ./log/client_log.log
    backupCount: 3
    maxBytes: 1000
    encoding: utf-8
loggers:
  client-logger:
    level: DEBUG
    handlers: [console, client-file]
    propagate: no
root:
  level: DEBUG
  handlers: [console]